### ISSUE TITLE
PhpStorm exception: Must not modify PSI inside save listener

### ISSUE THREAD

**Issue by mdio** [phpfmt/phpstorm-phpfmt#5] opened 2016-03-22 10:22 UTC
I don't know exactly what I was doing the moment the exception occurred but below is the stack trace.
I hope it helps. I could not reproduce the exception with the same file. I can share that file privatly if you'd like.

```
ERROR - .intellij.openapi.command.impl - Must not modify PSI inside save listener 
com.intellij.util.IncorrectOperationException: Must not modify PSI inside save listener
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:140)
	at com.intellij.psi.impl.DocumentCommitProcessor$2.run(DocumentCommitProcessor.java:224)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:682)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:124)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:717)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:924)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:713)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:679)
	at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:209)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:145)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:135)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:333)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:143)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:298)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:295)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:528)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:424)
	at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:390)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.psi.impl.PsiDocumentManagerBase.b(PsiDocumentManagerBase.java:382)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:284)
	at com.intellij.codeInsight.template.impl.TemplateState.a(TemplateState.java:759)
	at com.intellij.codeInsight.template.impl.TemplateState.access$3100(TemplateState.java:70)
	at com.intellij.codeInsight.template.impl.TemplateState$10$1.run(TemplateState.java:698)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:254)
	at com.intellij.codeInsight.template.impl.TemplateState$10.run(TemplateState.java:695)
	at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:181)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:166)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:183)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:173)
	at com.intellij.codeInsight.template.impl.TemplateState.calcResults(TemplateState.java:679)
	at com.intellij.codeInsight.template.impl.TemplateState.g(TemplateState.java:490)
	at com.intellij.codeInsight.template.impl.TemplateState.access$300(TemplateState.java:70)
	at com.intellij.codeInsight.template.impl.TemplateState$2$1.run(TemplateState.java:131)
	at com.intellij.codeInsight.template.impl.TemplateState$2.beforeCommandFinished(TemplateState.java:139)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.fireCommandFinished(CoreCommandProcessor.java:176)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.finishCommand(CoreCommandProcessor.java:161)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.finishCommand(CommandProcessorImpl.java:54)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:130)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.phpfmt.fmt.Formatter$1.run(Formatter.java:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.phpfmt.fmt.Formatter.Format(Formatter.java:84)
	at com.phpfmt.fmt.FileListener.beforeDocumentSaving(FileListener.java:25)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
	at com.sun.proxy.$Proxy22.beforeDocumentSaving(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor122.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:139)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:86)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:117)
	at com.sun.proxy.$Proxy22.beforeDocumentSaving(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$5.run(FileDocumentManagerImpl.java:454)
	at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:373)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.b(FileDocumentManagerImpl.java:451)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:425)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:345)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:324)
	at com.intellij.ide.SaveAndSyncHandlerImpl.doSaveDocumentsAndProjectsAndApp(SaveAndSyncHandlerImpl.java:140)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:134)
	at com.intellij.ide.SaveAndSyncHandlerImpl$4.onFrameDeactivated(SaveAndSyncHandlerImpl.java:104)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:87)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:72)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
ERROR - .intellij.openapi.command.impl - PhpStorm 10.0.3  Build #PS-143.1770 
ERROR - .intellij.openapi.command.impl - JDK: 1.8.0_40-release 
ERROR - .intellij.openapi.command.impl - VM: OpenJDK 64-Bit Server VM 
ERROR - .intellij.openapi.command.impl - Vendor: JetBrains s.r.o 
ERROR - .intellij.openapi.command.impl - OS: Mac OS X 
ERROR - .intellij.openapi.command.impl - Last Action: EditorBackSpace
```

**Comment by ccirello** [comment] 2016-03-23 18:05
@Shaked any insights?

**Comment by Shaked** [comment] 2016-03-24 10:01
@ccirello Sorry, I forgot to update. I have spoken to @mdio in private and for now we will be monitoring this issue. I believe that this issue is related to PhpStorm but I can't really be sure about it because we couldn't reproduce it. 

The only thing I have found is this:
https://github.com/krasa/eclipsecodeformatter/issues/65

**Comment by ccirello** [comment] 2016-04-08 01:53
Can we close this?

**Comment by Shaked** [comment] 2016-04-08 21:59
For now I think we can, if it happens again we should investigate more.

**Closed by Shaked** 2016-04-08 21:59 UTC
